/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.supermarket;

import java.io.File;
import java.io.FileInputStream;
import java.io.InputStream;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.swing.JRViewer;

/**
 *
 * @author kamal
 */
public class Product extends javax.swing.JFrame {

    /**
     * Creates new form Product1
     */
    public Product() {
        initComponents();
        GetCat();
        select();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        prodid = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        prodname = new javax.swing.JTextField();
        prodquan = new javax.swing.JTextField();
        addprod = new javax.swing.JButton();
        editprod = new javax.swing.JButton();
        deleteprod = new javax.swing.JButton();
        clearprod = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        producttable = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        prodprice = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        CatCb = new javax.swing.JComboBox<>();
        genarate = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(0, 153, 255));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 255));
        jLabel1.setText("MANEGE PRODUCTS");

        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 153, 255));
        jLabel2.setText("ProdID");

        prodid.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        prodid.setForeground(new java.awt.Color(0, 153, 255));
        prodid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prodidActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 153, 255));
        jLabel3.setText("Name");

        prodname.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        prodname.setForeground(new java.awt.Color(0, 153, 255));
        prodname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prodnameActionPerformed(evt);
            }
        });

        prodquan.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        prodquan.setForeground(new java.awt.Color(0, 153, 255));
        prodquan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prodquanActionPerformed(evt);
            }
        });

        addprod.setBackground(new java.awt.Color(0, 153, 255));
        addprod.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        addprod.setForeground(new java.awt.Color(255, 255, 255));
        addprod.setText("Add");
        addprod.setBorder(null);
        addprod.setBorderPainted(false);
        addprod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addprodActionPerformed(evt);
            }
        });

        editprod.setBackground(new java.awt.Color(0, 153, 255));
        editprod.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        editprod.setForeground(new java.awt.Color(255, 255, 255));
        editprod.setText("Edit");
        editprod.setBorder(null);
        editprod.setBorderPainted(false);
        editprod.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editprodMouseClicked(evt);
            }
        });
        editprod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editprodActionPerformed(evt);
            }
        });

        deleteprod.setBackground(new java.awt.Color(0, 153, 255));
        deleteprod.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        deleteprod.setForeground(new java.awt.Color(255, 255, 255));
        deleteprod.setText("Delete");
        deleteprod.setBorder(null);
        deleteprod.setBorderPainted(false);
        deleteprod.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deleteprodMouseClicked(evt);
            }
        });

        clearprod.setBackground(new java.awt.Color(0, 153, 255));
        clearprod.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        clearprod.setForeground(new java.awt.Color(255, 255, 255));
        clearprod.setText("Clear");
        clearprod.setBorder(null);
        clearprod.setBorderPainted(false);
        clearprod.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clearprodMouseClicked(evt);
            }
        });
        clearprod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearprodActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 153, 255));
        jLabel7.setText("Quantity");

        producttable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Name", "Quantity", "Price", "Category"
            }
        ));
        producttable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                producttableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(producttable);

        jLabel4.setFont(new java.awt.Font("Century Gothic", 1, 20)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 153, 255));
        jLabel4.setText("PRODUCTS LIST");

        jLabel5.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 153, 255));
        jLabel5.setText("PRICE");

        prodprice.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        prodprice.setForeground(new java.awt.Color(0, 153, 255));
        prodprice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prodpriceActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 153, 255));
        jLabel6.setText("CATEGORY");

        CatCb.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        CatCb.setForeground(new java.awt.Color(0, 153, 255));
        CatCb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));
        CatCb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CatCbActionPerformed(evt);
            }
        });

        genarate.setBackground(new java.awt.Color(0, 153, 255));
        genarate.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        genarate.setForeground(new java.awt.Color(255, 255, 255));
        genarate.setText("Genarete Report");
        genarate.setBorder(null);
        genarate.setBorderPainted(false);
        genarate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                genarateMouseClicked(evt);
            }
        });
        genarate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                genarateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(109, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(305, 305, 305))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(genarate, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(76, 76, 76)
                                .addComponent(jLabel4))
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(addprod, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(editprod, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(53, 53, 53)
                                    .addComponent(deleteprod, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(63, 63, 63)
                                    .addComponent(clearprod, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 619, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(87, 87, 87))))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(prodname, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(prodid, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(prodquan, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(prodprice, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(CatCb, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(prodid, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(prodquan, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(prodname, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(prodprice, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CatCb, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addprod, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(editprod, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deleteprod, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(clearprod, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(genarate, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );

        jLabel9.setFont(new java.awt.Font("Century Gothic", 1, 20)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("x");
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Century Gothic", 1, 20)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("SELLER");
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Century Gothic", 1, 20)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("CATEGORY");
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Century Gothic", 3, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Logout");
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel11MouseClicked(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Century Gothic", 1, 20)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("UPDATE");
        jLabel12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel12MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel11)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel10)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel9)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(159, 159, 159)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(93, 93, 93)
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 138, Short.MAX_VALUE)
                        .addComponent(jLabel11)
                        .addGap(34, 34, 34))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void prodidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prodidActionPerformed
        // TODO add your handling code here:.
    }//GEN-LAST:event_prodidActionPerformed

    private void prodnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prodnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_prodnameActionPerformed

    public void select() {
   try
    {
        DriverManager.registerDriver(new org.postgresql.Driver());
        String custr = "jdbc:postgresql://localhost:5432/postgres";
        String un = "amro";
        String up = "123456";
        Connection con = DriverManager.getConnection(custr, un, up);
        Statement stmt = con.createStatement();
        
        DefaultTableModel model = (DefaultTableModel) producttable.getModel();
        model.setRowCount(0);
        String query = "SELECT * FROM product order by productid"; // Query to select all columns
        ResultSet rs = stmt.executeQuery(query);

        while (rs.next()) {
            int ID = rs.getInt("productid");
            String Name = rs.getString("name");
            String Quantity = rs.getString("quantity");
            String Price = rs.getString("price");
             String Category = rs.getString("category");

            // Add a row to the table model
            model.addRow(new Object[]{ID, Name,Quantity,Price,Category});
        }  
    }catch(Exception ex)
    {
     JOptionPane.showMessageDialog(null, ex.toString());   
    } 
}
    
    
    private void prodquanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prodquanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_prodquanActionPerformed
 Connection con =null;   
 Statement st=null;
 ResultSet rs=null;
  private void GetCat()
  {
    try{
      String custr = "jdbc:postgresql://localhost:5432/postgres";
        String un = "amro";
        String up = "123456"; 
        con = DriverManager.getConnection(custr, un, up);
        st=con.createStatement();
        String query="SELECT * FROM Category ";
        rs=st.executeQuery(query);
        while(rs.next())
        {
         String Mycat=rs.getString("name");
         CatCb.addItem(Mycat);
        }
    }catch(Exception ex){
        ex.printStackTrace();
    }  
  }
    
    
    private void addprodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addprodActionPerformed
        if(prodid.getText().isEmpty() || prodname.getText().isEmpty()||prodquan.getText().isEmpty()||prodprice.getText().isEmpty())
        {
            JOptionPane.showMessageDialog(this, "Missing Information");
        }

        else {
            try {
                // TODO add your handling code here:
                DriverManager.registerDriver(new org.postgresql.Driver());
                String custr="jdbc:postgresql://localhost:5432/postgres";
                String un="amro";
                String up="123456";
                Connection con = DriverManager.getConnection(custr,un,up);
                con.setAutoCommit(false);
                Statement stmt = con.createStatement();
                //String prodid=this.prodid.getText();
               // String prodname=this.prodname.getText();
               // String prodquan=this.prodquan.getText();
              //  String prodprice=this.prodprice.getText();
                String prodcat=this.CatCb.getSelectedItem().toString();
                String strstmt="insert into Product values("+this.prodid.getText()+" , '"+this.prodname.getText()+"' , "+this.prodquan.getText()+", "+this.prodprice.getText()+" , '"+ prodcat+"')";
                stmt.executeUpdate(strstmt);
                con.commit();
                con.close();
                JOptionPane.showMessageDialog(this, "Product Added Successfuly");
                select();
                prodid.setText("");
                prodname.setText("");
                prodquan.setText("");
                prodprice.setText("");
            } catch (Exception ex) {
                //  Logger.getLogger(Product.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(null, ex.toString());
            }
        }
    }//GEN-LAST:event_addprodActionPerformed

    private void editprodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editprodActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editprodActionPerformed

    private void clearprodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearprodActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_clearprodActionPerformed

    private void prodpriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prodpriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_prodpriceActionPerformed

    private void CatCbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CatCbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CatCbActionPerformed

    private void producttableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_producttableMouseClicked
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) producttable.getModel();
        int Myindex=producttable.getSelectedRow();
        prodid.setText(model.getValueAt(Myindex, 0).toString());
        prodname.setText(model.getValueAt(Myindex, 1).toString());
         prodquan.setText(model.getValueAt(Myindex, 2).toString());
          prodprice.setText(model.getValueAt(Myindex, 3).toString());
          CatCb.setSelectedItem(model.getValueAt(Myindex, 4).toString());
        
    }//GEN-LAST:event_producttableMouseClicked

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        // TODO add your handling code here:
         System.exit(0);
    }//GEN-LAST:event_jLabel9MouseClicked

    private void clearprodMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clearprodMouseClicked
        // TODO add your handling code here:
         prodid.setText("");
        prodname.setText("");
        prodquan.setText("");
        prodprice.setText("");
        CatCb.setSelectedIndex(-1);
        
    }//GEN-LAST:event_clearprodMouseClicked

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        // TODO add your handling code here:
        new Seller().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel8MouseClicked

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
        // TODO add your handling code here:
         new Category().setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_jLabel10MouseClicked

    private void jLabel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseClicked
        // TODO add your handling code here:
         new login().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel11MouseClicked

    private void editprodMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editprodMouseClicked
        // TODO add your handling code here:
       if (prodid.getText().isEmpty() || prodname.getText().isEmpty() || prodquan.getText().isEmpty()|| prodprice.getText().isEmpty()) {
    JOptionPane.showMessageDialog(this, "Missing Information");
} else {
    try {
        DriverManager.registerDriver(new org.postgresql.Driver());
        String custr = "jdbc:postgresql://localhost:5432/postgres";
        String un = "amro";
        String up = "123456";
        Connection con = DriverManager.getConnection(custr, un, up);
        con.setAutoCommit(false);
        Statement stmt = con.createStatement();
        
        //String prodid = this.prodid.getText();
       // String prodname = this.prodname.getText();
       // String prodquan = this.prodquan.getText();
        //String prodprice = this.prodprice.getText();
        String prodcat = this.CatCb.getSelectedItem().toString();
        
        // SQL statement for updating category
        String strstmt = "UPDATE Product  SET name = '" + this.prodname.getText() + "', quantity = " + this.prodquan.getText() + ",price =" + this.prodprice.getText() + ",category = '" + prodcat + "'  WHERE productid = " + this.prodid.getText();
        
        int rowsUpdated = stmt.executeUpdate(strstmt);
        
        if (rowsUpdated > 0) {
            con.commit();
            JOptionPane.showMessageDialog(this, "Product Updated Successfully");
            select();
            prodid.setText("");
            prodname.setText("");
            prodquan.setText("");
            prodprice.setText("");
        } else {
            JOptionPane.showMessageDialog(this, "Product ID not found");
        }
        
        con.close();
        
    } catch (Exception ex) {
        JOptionPane.showMessageDialog(null, ex.toString());
    }
}
    }//GEN-LAST:event_editprodMouseClicked

    private void deleteprodMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteprodMouseClicked
        // TODO add your handling code here:
         if (prodid.getText().isEmpty()) {
          JOptionPane.showMessageDialog(this, "Please enter Category ID to delete");
         } else {
         try {
        DriverManager.registerDriver(new org.postgresql.Driver());
        String custr = "jdbc:postgresql://localhost:5432/postgres";
        String un = "amro";
        String up = "123456";
        Connection con = DriverManager.getConnection(custr, un, up);
        con.setAutoCommit(false);
        Statement stmt = con.createStatement();
        
        //String prodid = this.prodid.getText();
        
        // SQL statement for deleting category
        String strstmt = "DELETE FROM Product WHERE productid = " + this.prodid.getText();
        
        int rowsDeleted = stmt.executeUpdate(strstmt);
        
        if (rowsDeleted > 0) {
            con.commit();
            JOptionPane.showMessageDialog(this, "Product Deleted Successfully");
            select();
            prodid.setText("");
            prodname.setText("");
            prodquan.setText("");
            prodprice.setText("");
        } else {
            JOptionPane.showMessageDialog(this, "Product ID not found");
        }
        
        con.close();
        
    } catch (Exception ex) {
        JOptionPane.showMessageDialog(null, ex.toString());
    }
}

    }//GEN-LAST:event_deleteprodMouseClicked

    private void jLabel12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseClicked
        // TODO add your handling code here:
        new UpdateAdmin().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel12MouseClicked

    private void genarateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_genarateMouseClicked
        // TODO add your handling code here:
        try{
            String custr = "jdbc:postgresql://localhost:5432/postgres";
            String un = "amro";
            String up = "123456";
            DriverManager.registerDriver(new org.postgresql.Driver());
            Connection con = DriverManager.getConnection(custr, un, up);
            InputStream inp=new FileInputStream(new File("products.jrxml"));
            JasperDesign jd =JRXmlLoader.load(inp);
            JasperReport jr=JasperCompileManager.compileReport(jd);
            JasperPrint jp=JasperFillManager.fillReport(jr, null, con);
            //OutputStream os=new FileOutputStream(new File("rep.pdf")) ;
            //JasperExportManager.exportReportToPdfStream(jp, os);
            //os.close();
            JFrame frame =new JFrame("report");
            frame.getContentPane().add(new JRViewer(jp));
            frame.pack();
            frame.setVisible(true);
            con.close();
            inp.close();

        }catch(Exception ex){
            JOptionPane.showMessageDialog(null, ex.toString());
        }

    }//GEN-LAST:event_genarateMouseClicked

    private void genarateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_genarateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_genarateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Product.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Product.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Product.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Product.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Product().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CatCb;
    private javax.swing.JButton addprod;
    private javax.swing.JButton clearprod;
    private javax.swing.JButton deleteprod;
    private javax.swing.JButton editprod;
    private javax.swing.JButton genarate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField prodid;
    private javax.swing.JTextField prodname;
    private javax.swing.JTextField prodprice;
    private javax.swing.JTextField prodquan;
    private javax.swing.JTable producttable;
    // End of variables declaration//GEN-END:variables
}
