/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.supermarket;

import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.InputStream;
import java.io.OutputStream;
import java.sql.Connection;
import java.sql.Date;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperExportManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.swing.JRViewer;

/**
 *
 * @author kamal
 */
public class Seling extends javax.swing.JFrame {

    /**
     * Creates new form Seling
     */
    public Seling() {
        initComponents();
        GetCat();
         select();
         
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Genarete = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        billname = new javax.swing.JTextField();
        prodquan = new javax.swing.JTextField();
        addbill = new javax.swing.JButton();
        printbill = new javax.swing.JButton();
        Refrish = new javax.swing.JButton();
        clearbill = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        producttable = new javax.swing.JTable();
        CatCb = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        BillTxt = new javax.swing.JTextArea();
        Rs = new javax.swing.JLabel();
        Filter = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        Finish = new javax.swing.JButton();
        genarate = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(0, 153, 255));

        Genarete.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 255));
        jLabel1.setText("BILLIG POINT");

        jLabel3.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 153, 255));
        jLabel3.setText("Name");

        billname.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        billname.setForeground(new java.awt.Color(0, 153, 255));
        billname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                billnameActionPerformed(evt);
            }
        });

        prodquan.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        prodquan.setForeground(new java.awt.Color(0, 153, 255));
        prodquan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prodquanActionPerformed(evt);
            }
        });

        addbill.setBackground(new java.awt.Color(0, 153, 255));
        addbill.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        addbill.setForeground(new java.awt.Color(255, 255, 255));
        addbill.setText("Add To Bill");
        addbill.setBorder(null);
        addbill.setBorderPainted(false);
        addbill.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addbillMouseClicked(evt);
            }
        });
        addbill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addbillActionPerformed(evt);
            }
        });

        printbill.setBackground(new java.awt.Color(0, 153, 255));
        printbill.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        printbill.setForeground(new java.awt.Color(255, 255, 255));
        printbill.setText("Print");
        printbill.setBorder(null);
        printbill.setBorderPainted(false);
        printbill.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                printbillMouseClicked(evt);
            }
        });
        printbill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printbillActionPerformed(evt);
            }
        });

        Refrish.setBackground(new java.awt.Color(0, 153, 255));
        Refrish.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        Refrish.setForeground(new java.awt.Color(255, 255, 255));
        Refrish.setText("Refresh");
        Refrish.setBorder(null);
        Refrish.setBorderPainted(false);
        Refrish.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RefrishMouseClicked(evt);
            }
        });

        clearbill.setBackground(new java.awt.Color(0, 153, 255));
        clearbill.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        clearbill.setForeground(new java.awt.Color(255, 255, 255));
        clearbill.setText("Clear");
        clearbill.setBorder(null);
        clearbill.setBorderPainted(false);
        clearbill.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clearbillMouseClicked(evt);
            }
        });
        clearbill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearbillActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 153, 255));
        jLabel7.setText("Quantity");

        producttable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Name", "Quantity", "Price", "Category"
            }
        ));
        producttable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                producttableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(producttable);

        CatCb.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        CatCb.setForeground(new java.awt.Color(0, 153, 255));
        CatCb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CatCbMouseClicked(evt);
            }
        });
        CatCb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CatCbActionPerformed(evt);
            }
        });

        BillTxt.setColumns(20);
        BillTxt.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        BillTxt.setRows(5);
        jScrollPane1.setViewportView(BillTxt);

        Rs.setFont(new java.awt.Font("Century Gothic", 1, 20)); // NOI18N
        Rs.setForeground(new java.awt.Color(0, 153, 255));
        Rs.setText("       Rs");
        Rs.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        Filter.setBackground(new java.awt.Color(0, 153, 255));
        Filter.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        Filter.setForeground(new java.awt.Color(255, 255, 255));
        Filter.setText("Filter");
        Filter.setBorder(null);
        Filter.setBorderPainted(false);
        Filter.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                FilterMouseClicked(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Century Gothic", 1, 20)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 153, 255));
        jLabel5.setText("PRODUCT LIST");

        Finish.setBackground(new java.awt.Color(0, 153, 255));
        Finish.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        Finish.setForeground(new java.awt.Color(255, 255, 255));
        Finish.setText("Finish");
        Finish.setBorder(null);
        Finish.setBorderPainted(false);
        Finish.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                FinishMouseClicked(evt);
            }
        });
        Finish.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FinishActionPerformed(evt);
            }
        });

        genarate.setBackground(new java.awt.Color(0, 153, 255));
        genarate.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        genarate.setForeground(new java.awt.Color(255, 255, 255));
        genarate.setText("Genarete Report");
        genarate.setBorder(null);
        genarate.setBorderPainted(false);
        genarate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                genarateMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout GenareteLayout = new javax.swing.GroupLayout(Genarete);
        Genarete.setLayout(GenareteLayout);
        GenareteLayout.setHorizontalGroup(
            GenareteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(GenareteLayout.createSequentialGroup()
                .addContainerGap(543, Short.MAX_VALUE)
                .addGroup(GenareteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Rs, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(printbill, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(161, 161, 161))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, GenareteLayout.createSequentialGroup()
                .addGroup(GenareteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(GenareteLayout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addGroup(GenareteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(addbill, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(GenareteLayout.createSequentialGroup()
                                .addGroup(GenareteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7))
                                .addGap(29, 29, 29)
                                .addGroup(GenareteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(prodquan, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(billname, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(clearbill, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(genarate, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, GenareteLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Finish, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(107, 107, 107)))
                .addGroup(GenareteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(GenareteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel1)
                        .addComponent(jScrollPane2)
                        .addComponent(jScrollPane1))
                    .addGroup(GenareteLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(GenareteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5)
                            .addGroup(GenareteLayout.createSequentialGroup()
                                .addComponent(CatCb, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(31, 31, 31)
                                .addComponent(Filter, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(Refrish, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(42, 42, 42))
        );
        GenareteLayout.setVerticalGroup(
            GenareteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(GenareteLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(GenareteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(GenareteLayout.createSequentialGroup()
                        .addGroup(GenareteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CatCb, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Filter, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Refrish, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(GenareteLayout.createSequentialGroup()
                        .addGroup(GenareteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(billname, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(GenareteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(prodquan, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(37, 37, 37)
                        .addComponent(addbill, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(clearbill, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(genarate, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Finish, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(13, 13, 13)
                .addComponent(Rs, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(printbill, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );

        jLabel9.setFont(new java.awt.Font("Century Gothic", 1, 20)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("x");
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Century Gothic", 1, 20)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText(" Logout");
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 77, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Genarete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel9)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(Genarete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(78, 78, 78))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
 
     
  private void GetCat()
  {
    
    try{
      String custr = "jdbc:postgresql://localhost:5432/postgres";
        String un = "amro";
        String up = "123456"; 
        Connection con = DriverManager.getConnection(custr, un, up);
        Statement st=con.createStatement();
        String query="SELECT * FROM Category ";
        ResultSet rs=st.executeQuery(query);
        while(rs.next())
        {
         String Mycat=rs.getString("name");
         CatCb.addItem(Mycat);
        }
    }catch(Exception ex){
        ex.printStackTrace();
    }  
  }
    int Prid,newquan;
public void select() {
   try
    {
        DriverManager.registerDriver(new org.postgresql.Driver());
        String custr = "jdbc:postgresql://localhost:5432/postgres";
        String un = "amro";
        String up = "123456";
        Connection con = DriverManager.getConnection(custr, un, up);
        Statement stmt = con.createStatement();
        
        DefaultTableModel model = (DefaultTableModel) producttable.getModel();
        model.setRowCount(0);
        String query = "SELECT * FROM product order by productid"; // Query to select all columns
        ResultSet rs = stmt.executeQuery(query);

        while (rs.next()) {
            int ID = rs.getInt("productid");
            String Name = rs.getString("name");
            String Quantity = rs.getString("quantity");
            String Price = rs.getString("price");
             String Category = rs.getString("category");

            // Add a row to the table model
            model.addRow(new Object[]{ID, Name,Quantity,Price,Category});
        }  
    }catch(Exception ex)
    {
     JOptionPane.showMessageDialog(null, ex.toString());   
    } 
}





public void update() {
    try {
        String custr = "jdbc:postgresql://localhost:5432/postgres";
        String un = "amro";
        String up = "123456";
        Connection con = DriverManager.getConnection(custr, un, up);
        Statement st = con.createStatement();
        
       

        String query = "UPDATE Product SET quantity = " + newquan + " WHERE productid = " + Prid;
        st.executeUpdate(query); // Execute the update
        prodquan.setText("");
        billname.setText("");
        select();
        con.close();
    } catch (Exception ex) {
        JOptionPane.showMessageDialog(null, ex.toString());
    }
    
}  
    
Double Uprice,ProdTot=0.0,GrdTotal=0.0;
int Availquan;
    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jLabel9MouseClicked
int i=0;

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        // TODO add your handling code here:
        new login().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel4MouseClicked

    private void FilterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FilterMouseClicked
        // TODO add your handling code here:

        /* try {
            String custr = "jdbc:postgresql://localhost:5432/postgres";
            String un = "amro";
            String up = "123456";
            Connection con = DriverManager.getConnection(custr, un, up);
            Statement stmt = con.createStatement();
            String query = "SELECT * FROM Category WHERE name='" + CatCb.getSelectedItem().toString() + "'";
            stmt.executeUpdate(query);*/

            try {

                String custr = "jdbc:postgresql://localhost:5432/postgres";
                String un = "amro";
                String up = "123456";
                Connection con = DriverManager.getConnection(custr, un, up);
                Statement st = con.createStatement();
                String query = "SELECT * FROM Product WHERE category='" + CatCb.getSelectedItem().toString() + "'order by productid";
                ResultSet rs = st.executeQuery(query);

                // Get metadata to determine the number of columns and column names
                ResultSetMetaData rsMeta = rs.getMetaData();
                int columnCount = rsMeta.getColumnCount();

                // Create the DefaultTableModel with column names
                DefaultTableModel model = new DefaultTableModel();
                for (int i = 1; i <= columnCount; i++) {
                    model.addColumn(rsMeta.getColumnName(i));
                }

                // Populate the table model with data from the ResultSet
                while (rs.next()) {
                    Object[] row = new Object[columnCount];
                    for (int i = 1; i <= columnCount; i++) {
                        row[i - 1] = rs.getObject(i);
                    }
                    model.addRow(row);
                }

                // Set the model for the producttable
                producttable.setModel(model);

            } catch (Exception ex) {
                ex.printStackTrace();
            }
    }//GEN-LAST:event_FilterMouseClicked

    private void CatCbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CatCbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CatCbActionPerformed

    private void CatCbMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CatCbMouseClicked
        // TODO add your handling code here:

        try {
            String custr = "jdbc:postgresql://localhost:5432/postgres";
            String un = "amro";
            String up = "123456";
            Connection con = DriverManager.getConnection(custr, un, up);
            Statement st = con.createStatement();
            String query = "SELECT * FROM category WHERE name='" + CatCb.getSelectedItem().toString() + "'";
            ResultSet rs = st.executeQuery(query);

            // DefaultTableModel model = new DefaultTableModel();
            // producttable.setModel(model);

        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_CatCbMouseClicked

    private void producttableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_producttableMouseClicked
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) producttable.getModel();
        int Myindex=producttable.getSelectedRow();
        Prid=Integer.parseInt(model.getValueAt(Myindex, 0).toString());
        billname.setText(model.getValueAt(Myindex, 1).toString());
        Availquan=Integer.parseInt(model.getValueAt(Myindex, 2).toString());
        Uprice=Double.valueOf(model.getValueAt(Myindex, 3).toString());
        //newquan=(Availquan - Integer.parseInt(prodquan.getText()));
        ProdTot =Uprice*Integer.valueOf(prodquan.getText());
        // prodquan.setText(model.getValueAt(Myindex, 3).toString());
        //  prodprice.setText(model.getValueAt(Myindex, 4).toString());
    }//GEN-LAST:event_producttableMouseClicked

    private void clearbillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearbillActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_clearbillActionPerformed

    private void clearbillMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clearbillMouseClicked
        // TODO add your handling code here:
        //billid.setText("");
        billname.setText("");
        //prodid.setText("");
        prodquan.setText("");
        //CatCb.setSelectedIndex(-1);
        select();
    }//GEN-LAST:event_clearbillMouseClicked

    private void RefrishMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RefrishMouseClicked
        // TODO add your handling code here:
       // billid.setText("");
        billname.setText("");
        //prodid.setText("");
        prodquan.setText("");
        // CatCb.setSelectedIndex(-1);
        select();
    }//GEN-LAST:event_RefrishMouseClicked

    private void printbillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printbillActionPerformed
        // TODO add your handling code here:
        try{
            BillTxt.print();
        }catch(Exception ex)
        {

        }
    }//GEN-LAST:event_printbillActionPerformed

    private void printbillMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_printbillMouseClicked
        // TODO add your handling code here:
        try{
            BillTxt.print();
        }catch(Exception ex){

        }
    }//GEN-LAST:event_printbillMouseClicked

    private void addbillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addbillActionPerformed

    }//GEN-LAST:event_addbillActionPerformed

    private void addbillMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addbillMouseClicked

        if (prodquan.getText().isEmpty() || billname.getText().isEmpty()||prodquan.getText().equals("0")) {
            JOptionPane.showMessageDialog(this, "Missing Information");
        } 
        newquan=(Availquan - Integer.parseInt(prodquan.getText()));
        if (Availquan < Integer.parseInt(prodquan.getText())) {
            JOptionPane.showMessageDialog(this, "Not Enough In Stock");
        } 
        else {
            i++;
            ProdTot = Uprice * Double.valueOf(prodquan.getText());
            GrdTotal += ProdTot;
            if(i == 1) {
                BillTxt.setText(BillTxt.getText()+"                                ------- FAMILY POINT -------\n"+"NUM     PRODUCT     QUANTITY     PRICE     TOTAL\n"+i+"             "+billname.getText()+"              "+prodquan.getText()+"               "+Uprice+"           "+ProdTot+"\n");
            }
            else
            {
                BillTxt.setText(BillTxt.getText()+i+"             "+billname.getText()+"              "+prodquan.getText()+"               "+Uprice+"           "+ProdTot+"\n");
            }
            Rs.setText("Rs" + GrdTotal);
            update();
        }
       
    }//GEN-LAST:event_addbillMouseClicked

    private void prodquanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prodquanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_prodquanActionPerformed

    private void billnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_billnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_billnameActionPerformed

    private void FinishMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FinishMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_FinishMouseClicked

    private void FinishActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FinishActionPerformed
        // TODO add your handling code here:
        try {
        // Establish connection to the database
        String custr = "jdbc:postgresql://localhost:5432/postgres";
        String un = "amro";
        String up = "123456";
        Connection con = DriverManager.getConnection(custr, un, up);
        con.setAutoCommit(false);

        // Prepare the SQL statement with placeholders (excluding billid for auto-increment)
        String strstmt = "INSERT INTO bill (amount, date) VALUES (?, ?)";
        PreparedStatement pstmt = con.prepareStatement(strstmt);

        // Set the amount and current date
        pstmt.setDouble(1, this.GrdTotal);
        pstmt.setDate(2, java.sql.Date.valueOf(LocalDate.now())); // Uses the current date in the correct format for SQL

        // Execute the insertion
        pstmt.executeUpdate();

        // Commit and close connection
        con.commit();
        con.close();

        // Show success message
        JOptionPane.showMessageDialog(this, "You Are Finishing");

    } catch (Exception ex) {
        // Display any exceptions in a message dialog
        JOptionPane.showMessageDialog(null, ex.toString());
    }

    // Optionally, exit the program
    System.exit(0);
        
    }//GEN-LAST:event_FinishActionPerformed

    private void genarateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_genarateMouseClicked
        // TODO add your handling code here:
        try{
            String custr = "jdbc:postgresql://localhost:5432/postgres";
            String un = "amro";
            String up = "123456";
            DriverManager.registerDriver(new org.postgresql.Driver());
            Connection con = DriverManager.getConnection(custr, un, up);
            InputStream inp=new FileInputStream(new File("seling.jrxml"));
            JasperDesign jd =JRXmlLoader.load(inp);
            JasperReport jr=JasperCompileManager.compileReport(jd);
            JasperPrint jp=JasperFillManager.fillReport(jr, null, con);
            //OutputStream os=new FileOutputStream(new File("rep.pdf")) ;
            //JasperExportManager.exportReportToPdfStream(jp, os);
            //os.close();
            JFrame frame =new JFrame("report");
            frame.getContentPane().add(new JRViewer(jp));
            frame.pack();
            frame.setVisible(true);
            con.close();
            inp.close();

        }catch(Exception ex){
            JOptionPane.showMessageDialog(null, ex.toString());
        }
    }//GEN-LAST:event_genarateMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Seling.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Seling.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Seling.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Seling.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Seling().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea BillTxt;
    private javax.swing.JComboBox<String> CatCb;
    private javax.swing.JButton Filter;
    private javax.swing.JButton Finish;
    private javax.swing.JPanel Genarete;
    private javax.swing.JButton Refrish;
    private javax.swing.JLabel Rs;
    private javax.swing.JButton addbill;
    private javax.swing.JTextField billname;
    private javax.swing.JButton clearbill;
    private javax.swing.JButton genarate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton printbill;
    private javax.swing.JTextField prodquan;
    private javax.swing.JTable producttable;
    // End of variables declaration//GEN-END:variables
}
